### ISSUE TITLE
Forma de Pagamento - API Jueri

### ISSUE THREAD

**Issue by gabrielrbarbosa** [MVinicius3091/jueri-desafio#1]
Boa tarde Maykon Vinicius!! 
Bem completo o desafio de integração com o Jueri!

Apenas um detalhe no checkout a API do Jueri deve receber a forma de pagamento como object único e o boleto como array de objetos, basta inverter no [Checkout](https://github.com/MVinicius3091/jueri-desafio/blob/c4fade1f061d1740ab2b109507c12a2d3cc9b0b6/app/controller/ApiController.php#L151).

**Comment by gabrielrbarbosa** [comment]
@MVinicius3091 no arquivo bootstrap.php acredito que dê para utilizar a constante CLIENT_PARAM do .env também!

**Comment by MVinicius3091** [comment]
Boa tarde, obg pelo feedback.... 
Tentei manter um padrão no cors do código, mas foi apertando o tempo daí eu tive pouco tempo pra revisar... De qualquer forma foi um grande desafio!!

**Comment by MVinicius3091** [comment]
Sobre o .env no bootstrap.php passou desapercebido mesmo...
